# Базовый образ Apache Airflow
FROM apache/airflow:2.10.3

# Используем пользователя root для установки системных зависимостей
USER root

# Устанавливаем необходимые зависимости для Playwright
RUN apt-get update && apt-get install -y \
    curl \
    libx11-xcb1 \
    libglib2.0-0 \
    libnss3 \
    libatk1.0-0 \
    libgdk-pixbuf2.0-0 \
    libxcomposite1 \
    libxrandr2 \
    libasound2 \
    libpangocairo-1.0-0 \
    libatk-bridge2.0-0 \
    libxss1 \
    libappindicator3-1 \
    libnspr4 \
    libgbm1 \
    libdrm2 \
    && rm -rf /var/lib/apt/lists/*

# Переключаемся на пользователя airflow для установки Python-зависимостей
USER ${AIRFLOW_UID}

# Устанавливаем Playwright для Python
RUN pip install playwright

# Устанавливаем браузеры для Playwright
RUN playwright install
